# Override for CI/CD environments
# Removes local mounts and DevTools for smooth CI builds

version: '3.8'

services:
  modern-web-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev

    # Only expose the necessary port for tests
    ports:
      - "8080:8080"

    # ❌ Do not mount local code in CI
    volumes: []

    # Environment suitable for CI
    environment:
      - SPRING_PROFILES_ACTIVE=ci
      - SPRING_DEVTOOLS_RESTART_ENABLED=false
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=false
      - JAVA_TOOL_OPTIONS=-Xmx1g

    # Faster healthcheck for CI
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

    stdin_open: false
    tty: false
    restart: on-failure
